language: c

# To use Travis CI's newer container infrastructure, use the following
# line. (Also be sure RACKET_DIR is set to somewhere like ~/racket
# that doesn't require sudo.)
sudo: false

env:
  global:
    # Supply a global RACKET_DIR environment variable. This is where
    # Racket will be installed. A good idea is to use ~/racket because
    # that doesn't require sudo to install and is therefore compatible
    # with Travis CI's newer container infrastructure.
    - RACKET_DIR=~/racket
  matrix:
    # Supply at least one RACKET_VERSION environment variable. This is
    # used by the install-racket.sh script (run at before_install,
    # below) to select the version of Racket to download and install.
    #
    # Supply more than one RACKET_VERSION (as in the example below) to
    # create a Travis-CI build matrix to test against multiple Racket
    # versions.
    #
    # The RELEASE snapshot is only available during the release process.
    - RACKET_VERSION=6.0
    - RACKET_VERSION=6.1
    - RACKET_VERSION=6.2
    - RACKET_VERSION=6.3
    - RACKET_VERSION=6.4


# You may want to test against certain versions of Racket, without
# having them count against the overall success/failure.
matrix:
  # Fast finish: Overall build result is determined as soon as any of
  # its rows have failed, or, all of its rows that aren't allowed to
  # fail have succeeded.
  fast_finish: true


before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
  - export PATH="${RACKET_DIR}/bin:${PATH}" # install-racket.sh can't set for us

install:

before_script:

# Here supply steps such as raco make, raco test, etc.
#
# Tip: Use `raco pkg install --deps search-auto <pkg>` to install any
# required packages without getting stuck on a confirmation prompt.
script:
  - bash test.sh

# NOTE: If your repo is a Racket package with an info.rkt that
# includes some `deps`, the following is more elegant:
#
# script:
# - cd ..   # Travis did a cd into the dir. Back up, for the next:
# - raco pkg install --deps search-auto --link <pkg>
# - raco test -x -p <pkg>

after_script:
  - bash distribute.sh

deploy:
  provider: releases
  api_key:
    secure: RjQuJuVEm4qDGjb8zffgDnbWfyl0y3Fe0Oku399XT71EA9N22FvaGOeS5Z7e9pIdspwPH/0AffYlqiXzW8Av89X3o2IeSyFHHvk3TZhu91tW4R5wTgd9SqqPc9RPasGw2lEB/CzjSvBQ/Gb8anHXRfokfeuunqTfZ0N2OTfDKl0o7igYSqYo996BMjlFgf5e726SZCy6Z3VN7fFHoPE7DPRPsQy/o2uxswXtDH7KbqexstR/u8TSRch5yu9XMlkUu24xZlh8n0QgzaRVtjIp2GIKUui9lNjew5sCIgFe/KxRDyMQArFb4eyGjVrxeb8Ytk6cKqItIrDVUWoK1x5pg6FUigET0FGM6GeWUlSIakapOB7h6PchX3l0SOR0WAfNDBSMtDZ+r+GvBSnlv5f4CCaDbfW0tow3mgWgzk6fAiNSRueUjt5OeyL1BkR0sYeoehE/R2fG17KnNk8XKIzO6aVQQTdyoP1jXVaTKgNEA996jFI2s2/O1wN5rk7BNI3UyFEkAWXpfJ+xPp9KQ4pzg0Z5DkwhnAsn6K4mBLbKKX+SydDvLIhLLHXYn1CDBJgODI27cyTB/IZRn0WFJdQnplGRiXl2Bv82rn1erEMqI1GMpuEpgYFRHO/0PRAXN3h5ZuWBDw1bRsyLV1w5P8sYMKe8X5FZiVnUUPGPm2hQrtc=
  file: tic-tac-toe.zip
  skip_cleanup: true
  on:
    repo: mafagafogigante/tic-tac-toe
    tags: true
